#import "../../macros.typ": *

//setup basics
#import "@preview/rubber-article:0.4.1": *
#import "@preview/ergo:0.2.0": *
#import "@preview/fletcher:0.5.5" as fletcher: *

//basic template setup
#show: article.with(
  header-display: true,
  eq-numbering: "(1.1)",
  eq-chapterwise: true,
  margins: 1.0in,
)
#show: ergo-init.with(
    colors: ergo-colors.bw,  
    styles: ergo-styles.basic, 
    breakable: true,
    inline-qed: true
)

//start document
#maketitle(
  title: "Math 237B Midterm",
  authors: ("Zih-Yu Hsieh",),
  date: datetime.today().display("[month repr:long] [day], [year]"),
)

#set enum(numbering: "(1)")

= D//1
#problem[
  Let $A=CC[x,y]\/(f(x,y))$ and consider the scheme $X=Spec(A)$. Prove or disprove that there is a finite set $S subset X$ such that every connected component of $X\\S$ is irreducible as a topological space.

  \ 

  #line(length: 100%)

  \ 
][
  /*Guess: True, consider removing the intersection of each irreducible factor of $f(X,Y)$. If $g, h$ are two irreducible polynomials in $CC[x,y]$ that're distinct, try and argue that their set of solutions must be distinct (transferring to $CC^2$ with Zariski Topology may be hard, but can use this as an intuition check)

  Question: Can we find a Noetherian integral domain $B$ with Krull Dimension 1, such that $Spec(B)\\S$ for finite set $S$ ($S$ closed), but irreducible components and connected components differ?

  \ 

  An integral domain with infinite maximal ideals has its spec being irreducible (hence connected). What happens if removing only finitely many points? (removing finitely many points, then it's an open subset, hence irreducible, hence connected). So, such reduction is in fact connected!

  \ 

  #line(length: 100%)

  \ 
  */
  We'll prove there exists a finite set $S subset X$, such that all connected component of $X\\S$ is irreducible as topological space.

  \ 

  First, let's cover some special cases like $f=0$ or $f=a$ for some nonzero $a in CC$:
  - If $f=0$, then $A=CC[x,y]$ (an integral domain), as a result $X = Spec(A)$ is irreducible, hence connected. Take $S=emptyset$, then $X\\S = X$ has itself being a connected component, which is irreducible.
  - If $f=a$ ($a!=0$ in $CC$), then $A = 0$ as an abelian group (since $(f(x,y))=CC[x,y]$). So, $Spec(A)=emptyset$ is a trivial case we can ignore.

  Hence now on, we'll assume $f$ is a non-constant polynomial.

  \ 

  Given that $A=CC[x,y]\/(f(x,y))$, one knows that $X=Spec(A) tilde.equiv V((f)) subset Spec(CC[x,y])$ as subspace topology. Hence, we'll mainly work with this subspace.

  The proof will follow this order:
  1. Show that $V((f)) = union.big_i V(P_i)$ for finitely many distinct prime ideals $P_i$.
  2. Show that $S:= union.big_((i_1,...,i_k))(sect.big_(j=1)^k V(P_(i_j)))$, i.e. the union of any intersection of distinct $V(P_i)$'s, is a finite set, and moreover only contains maximal ideals.
  3. Show that $X\\S = (union.big_i V(P_i))\\S = union.sq.big_i (V(P_i)\\S)$, and each $V(P_i)\\S$ is irreducible (hence connected).
  4. Deduce that each $V(P_i)\\S$ must be the connected component of $X\\S$, hence $X\\S$ has all connected components being irreducible as topological spaces.

  \ 

  #text(weight: "bold")[Proof of (1):]

  First, recall that $CC[x,y]$ is a UFD, hence $f(x,y) = product_(i=1)^n (f_i (x,y))^(k_i)$ for finitely many non-associate irreducible polynomials $f_1,...,f_n in CC[x,y]$, and some powers $k_1,...,k_n in NN\\{0}$. For each index $1<=i<=n$, define the prime ideal $P_i := (f_i (x,y))$, which $i!=j$ implies $P_i != P_j$ (since their generators are non-associates). Notice that since $f$ is divisible by each $f_i$, one has $(f) subset.eq (f_i)=P_i$ for all index $i$. 
  
  Now, we claim that $V((f)) = union.big_(i=1)^n V(P_i)$:
  - Given any prime ideal $Q in union.big_(i=1)^n V(P_i)$, since there exists index $i$ such that $Q in V(P_i)$, one has $P_i subset.eq Q$; as a result, $(f) subset.eq P_i subset.eq Q$, showing $Q in V((f))$. Hence, $union.big_(i=1)^n V(P_i) subset.eq V((f))$.
  - Conversely, for any prime ideal $Q' in V((f))$, since $product_(i=1)^n f_i = f in (f) subset.eq Q'$, then there exists index $i$ with $f_i in Q'$ based on the prime property. Hence, $P_i=(f_i) subset.eq Q'$, showing $Q' in V(P_i)$. So, $V((f)) subset.eq union.big_(i=1)^n V(P_i)$.

  This provides the desired finite union, or $X = V((f)) = union.big_(i=1)^n V(P_i)$.

  \ 

  #text(weight: "bold")[Proof of (2):]

  To prove (2), it suffices to show that $i!=j$ implies $V(P_i) sect V(P_j)$ is finite (since all arbitrary intersections of $V(P_i)$'s is contained in some $V(P_i) sect V(P_j)$ for $i!=j$; if each such pair is finite, with finitely many pairs of $(i,j)$ possible, $S$ must also be finite).

  For any $i!=j$, recall that $P_i, P_j$ are distinct nonzero prime ideals (since they're generated by irreducible polynomials, hence nonzero). Since the Krull Dimension of $CC[x,y]$ is $2$, then each of the nonzero prime ideal must have height $1$ or $2$ (since $"height"(P) <= dim(CC[x,y])$, and $P!=0$ implies $"height"(P)>0$). 

  \ 

  - If one of $P_i, P_j$ has height $2$ (WLOG, say $P_i$ has height $2$), since it matches the dimension of $CC[x,y]$, this indicates that $P_i$ is in fact maximal. So, $V(P_i)= {P_i}$ is a singleton (since the only prime ideal that can contain $P_i$ a maximal ideal, is $P_i$ itself). Hence, $V(P_i) sect V(P_j)$ must be finite (either empty, or singleton that consists of $P_i$, the maximal ideal).

  \ 

  - Else if both $P_i, P_j$ has height $1$, then for any prime ideal $M in V(P_i) sect V(P_j)$, because it properly containes $P_i, P_j$ (due to the fact that $P_i!=P_j$), then $M$ must have height $>1$ and $<=2$, which has height $2$. This implies that $M$ is a maximal ideal of $CC[x,y]$. But, by Hilbert's Nullstellensatz, we know $M = (x-a, y-b)$ for some $a,b in CC$ (since $CC$ is algebraically closed), in particular, with $f_i, f_j in M$, this implies $f_i (a,b) = f_j (a,b)=0$. Hence, $(a,b) in CC^2$ is a common zero for $f_i,f_j$.
    
    Now, recall that for the zero sets $Z(P_i) = Z(f_i)$ and $Z(P_j)=Z(f_j)$ are distinct irreducible closed curves in $CC^2$ (under Zariski Topology, since $P_i, P_j$ are prime), hence their intersection $Z(P_i) sect Z(P_j)$ is in fact finite. Which, this intersection is precisely all pairs $(a,b) in CC^2$, where $f_i (a,b)=f_j (a,b)=0$. Therefore, since they share finitely many common zeros, this implies there are also finite maximal ideals $M=(x-a,y-b) in V(P_i) sect V(P_j)$.

    \ 

  Since in each case $V(P_i) sect V(P_j)$ (for $i!=j$) is finite, and there are finitely many pairs of distinct $i,j$, then the set $S$ collecting all nontrivial intersections between $V(P_i)$'s is also a finite set. Also, within the proof we've indicated that every such nontrivial intersection must consist of maximal ideals. Hence, $S$ is a finite set of maximal ideals.

  \ 

  #text(weight: "bold")[Proof of (3):]

  Now, consider the set $X\\S$. Using (1) and (2), we get it's the same as $(union.big_(i=1)^n V(P_i))\\S = union.big_(i=1)^n (V(P_i)\\S)$. However, notice that $S$ contains all the nontrivial intersection of each $V(P_i)$'s, hence one has $(V(P_i)\\S) sect (V(P_j)\\S) = emptyset$ for all $i!=j$. Therefore, $X\\S = union.sq.big_(i=1)^n (V(P_i)\\S)$, where each subset $V(P_i)\\S = V(P_i) sect (X\\S)$ is closed in $X\\S$ under its subspace topology.

  Given that each $P_i subset CC[x,y]$ is a prime ideal, then $V(P_i) tilde.equiv Spec(CC[x,y]\/P_i)$ as topological spaces is irreducible (since $CC[x,y]\/P_i$ is an integral domain, its prime spectrum is irreducible, a proposition proven in class). 
  
  Which, 
  /*there are two cases to consider:

  \ 

  - If $P_i$ is maximal, then $CC[x,y]\/P_i$ is a field, which $V(P_i) tilde.equiv Spec(CC[x,y]\/P_i)$ is a singleton. Then, $V(P_i)\\S$ is either an emptyset (which we'll ignore if happens) or singleton, which is vacuously irreducible.

  \ 

  - Else if $P_i$ is not maximal, notice that the set $V(P_i)$ is infinite (since classically there are infinitely many pairs $(a,b) in CC^2$ satisfying $f_i (a,b)=0$, as a consequence each maximal ideal $M=(x-a,y-b) in V(P_i)$). In particular,*/ 
  since the set $S$ collects finitely many maximal ideals (which $M in S$ a maximal ideal implies ${M} = V(M)$ is a closed set), hence $S$ is a finite union of closed points, which is also closed in $Spec(CC[x,y])$.

  As a result, $V(P_i)\\S = V(P_i)\\(V(P_i) sect S)$ is open under its own subspace topology. So, if it's nonempty (we'll ignore the empty ones), $V(P_i)\\S subset.eq V(P_i)$ is an open subset of an irreducible space, hence is also irreducible.

  This concludes that each $V(P_i)\\S$ is irreducible (which is also connected).

  \ 

  #text(weight: "bold")[Proof of (4):]

  Finally, with $X\\S = union.big.sq_(i=1)^n (V(P_i)\\S)$, each nonempty $(V(P_i)\\S) subset.eq (X\\S)$ is closed, irreducible, and connected (by (3)). Then, each nonempty $V(P_i)\\S$ must be a connected component: Suppose $(V(P_i)\\S) subset.eq U$ for some connected subset $U subset.eq (X\\S)$. As a result, $U = U sect (X\\S) = union.sq.big_(i=1)^n (U sect (V(P_i)\\S))$. Since each $V(P_i)\\S$ is disjoint from each other, $U$ here is written as a finite disjoint union of closed subsets (under subspace topology of $U$). Which, by connectedness, with $V(P_i)\\S subset.eq U$ being nonempty, the other $j!=i$ must have $U sect (V(P_j)\\S) = emptyset$. Hence, $U = U sect (V(P_i)\\S)$, showing that $U subset.eq V(P_i)\\S$, or $U=V(P_i)\\S$.

  Hence, each nonempty $V(P_i)\\S$ is indeed a connected component of $X\\S$ that's irreducible; then, with $X\\S = union.sq.big_(i=1)^n (V(P_i)\\S)$, the nonempty $V(P_i)\\S$ must be all the connected components, showing $S$ is a finite set which $X\\S$ has all connected component being irreducible. #place(right, $ballot$)
]

#pagebreak()

= D//2
#problem[
  Let $f:X->Y$ be a morphism of integral schemes which is a topological homeomorphism. Prove or disprove that $f$ is an isomorphism of schemes.

  \ 

  #line(length: 100%)

  \ 

][
  /*
  Possibly needed information: integral schemes $<==>$ it's reduced and irreducible. We know it's a homeomorphism on each affine cover. If we can prove that it transfer fundamental open subsets of each affine cover to another one (that're isomorphic), then I think we're done.

  \ 

  In the notes there's a move, choosing a local integral domain $A$ not a field, take its fraction field $F(A)$, then take the 1-pt space with these two as constant sheaves. Which, identity on $X$ induces the inclusion $A arrow.hook F(A)$, but it's not a local homomorphism (so it's not a morphism between locally ringed space).

  \ 

  Based on this, if one has two local integral domains, a local homomorphism that's not an isomorphism maybe is a counterexample.

  \

  #text(weight: "bold")[Answer:] Consider the case between spec of two fields.
  */
  We'll disprove the statement by constructing a counterexample.

  \ 

  Consider the field inclusion $iota: RR arrow.hook CC$, which generates the pullback map $iota^*:Spec(CC) -> Spec(RR)$. 
  
  First, notice that because $RR,CC$ are both fields, the $Spec(CC), Spec(RR)$ are both singleton set, hence as continuous maps between topological spaces, $iota^*$ is a topological homeomorphism. 
  
  Second, since they're singletons, then the only nonempty open subsets are $Spec(CC)$ and $Spec(RR)$ themselves, so one deduces $cal(O)(Spec(CC)) = CC$ and $cal(O)(Spec(RR)) = RR$, which both are integral domains. Hence, these two spaces have all the nonempty open neighborhoods corresponding to an integral domain using their structure sheaves, showing $Spec(CC)$ and $Spec(RR)$ are integral schemes.

  \ 

  Yet, it's not an isomorphism as schemes: Suppose the contrary that it's an isomorphism of schemes, there exists another morphism of integral schemes $j:Spec(RR) -> Spec(CC)$, such that it's not only an inverse of $iota^*$, but its induced ring homomorphism $j^*:cal(O)(Spec(CC))-> cal(O)(Spec(RR))$ is the inverse of the ring homomorphism $(iota^*)^*:cal(O)(Spec(RR))-> cal(O)(Spec(CC))$. However, the induced ring homomorphism of $iota^*$, or $(iota^*)^*$, is precisely the inclusion $iota:RR arrow.hook CC$; since $j^*:CC -> RR$ is its inverse, they imply that $RR$ and $CC$ are isomorphic fields. 
  
  This is a contradiction, because consider $i in CC$, its multiplicative order is $4$ (since $i^4 = 1$, and any positive integer $n<4$ has $i^n!=1$); however, there's no element in $RR$ with multiplicative order of $4$ (since if $x in RR$ satisfies $x^4 = 1$, then $x^4-1 = (x-1)(x+1)(x^2+1)=0$; with $x^2+1=0$ having no solution in $RR$, then $x=pm 1$, which it either has multiplicative order of $1$ or $2$, not $4$). hence, $RR, CC$ can't be isomorphic fields, leading to a contradiction.

  So, since we derive a contradiction, $iota^*:Spec(CC)-> Spec(RR)$ can't be an isomorphism of schemes, despite it's a topological homeomorphism. #place(right, $ballot$)
]

#pagebreak()

= D//3
#problem[
  Let $k$ be a countable field and let $f:X -> Spec(k)$ be a finite type morphism of schemes. Prove or disprove hat $X$ has at most countably many points.

  \ 

  #line(length: 100%)

  \ 
][
  /*Claim 1: $X$ is Noetherian (because $Spec(k)$ is affine + quasi-compact (a single point), while the morphism is finite type). So, one only needs to find finitely many affine cover for $X$ (because $X$ Noetherian $==>$ Quasi-compact).

  Claim 2: Each affine cover can be chosen, so that $U_i-> Spec(k)$ is induced by a finite type ring homomorphism $k -> cal(O)(U)$, showing $cal(O)(U)$ is a quotient of polynomial rings with finitely many variables. So, want to claim it's countable, one needs to claim that $k[x_1,...,x_n]$ has countable prime ideals.

  However, this is true as one can use the unique factorizatoin property to claim that a prime ideal is created by finitely many irreducibles, so if there are countable irreducibles, there are countable prime ideals.

  \ 
  */
  We'll prove that $X$ has at most countably many points.

  \ 

  First, since $Spec(k)$ is an affine scheme, and $k$ is a field (which is Noetherian), it's a locally Noetherian Scheme. Moreover, $Spec(k)$ is a singleton, hence quasi-compact, so $Spec(k)$ is a Noetherian scheme. Which, with $f:X -> Spec(k)$ being a finite type morphism and $Spec(k)$ being a Noetherian scheme, $X$ must be Noetherian also (based on a theorem proven in class).

  \ 

  Then, using the definition of finite type morphism, there exists an affine cover ${U_i}$ of $Spec(k)$, each $U_i$ corresponds to finite affine open subset ${U_(i j)}$ in $X$, such that $f^(-1)(U_i) = union.big_(j)U_(i j)$, and the induced ring homomorphism $cal(O)(U_i) -> cal(O)(U_(i j))$ is a finite type ring homomorphism. 
  
  Notice that since $Spec(k)$ is compact, the list ${U_i}$ can be chosen to be finite (moreover, with $Spec(k)$ being singleton, it can be chosen to be a single set $U$). Which, since $U$ covers $Spec(k)$, one has $U = Spec(k)$, deducing that $cal(O)(U) = cal(O)(Spec(k))=k$. So, given that $f^(-1)(U)=f^(-1)(Spec(k)) = X$, one has $X = union.big_(j)U_j$ for finitely many affine open subsets $U_j$, and each induced ring homomorphism $cal(O)(U) -> cal(O)(U_j)$ is of finite type. 

  With $cal(O)(U) = k$, then the given ring homomorphism is of finite type implies there exists a surjective $k$-algebra homomorphism $k[x_1,...,x_n]->> cal(O)(U_j)$, where $n$ is a finite number (in other words, each $cal(O)(U_j)$ is a quotient of finite-variable polynomial rings over $k$).

  \ 

  Now, we claim that each $U_j$ is in fact countable: Based on the above fact, with $cal(O)(U_j)$ being a quotient of $k[x_1,...,x_n]$ for some finite $n$, then $U_j = Spec(cal(O)(U_j))$ can be interpreted as a subset of $Spec(k[x_1,...,x_n])$ (since given a commutative ring $A$ with an ideal $I subset A$, ${"ideal" J subset.eq A\/I}$ and ${"ideal" K subset A | I subset.eq K}$ are of bijective correspondance, while preserving prime ideals). Hence, to prove $U_j$ is countable, it suffices to prove that $Spec(k[x_1,...,x_n])$ is countable (given that $k$ is a countable field). We'll prove it as follow:

  \ 

  1. #text(weight: "bold")[$k[x_1,...,x_n]$ is countable, given that $k$ is countable:] 
  
    Here we'll approach by induction on the number of variables $n$. For $n=1$, recall that every polynomial $f(x) in k[x]$ is of bounded degree, hence there exists $i in NN$, such that $f(x) in plus.circle.big_(n=0)^i k x^n$, which is isomorphic to $plus.circle.big_(n=0)^i k$. Because finite product of countable sets is countable, and finite product coincides with direct coincides for abelian groups, one has $plus.circle.big_(n=0)^i k x^n$ being countable. As a result, $k[x] = union.big_(i=0)^infinity (plus.circle.big_(n=0)^i k x^i)$ is a countable union of countable sets, hence countable.

    Now, suppose for given $n in NN$, all $j<n$ satisfies $k[x_1,...,x_j]$ being countable, then for $k[x_1,...,x_n]$, interpret as the polynomial ring $(k[x_1,...,x_(n-1)])[x_n]$. Because $k[x_1,...,x_(n-1)]$ is countable by induction hypothesis, apply the proof for the case $n=1$, we obtained that $k[x_1,...,x_n]$ (as a single-variable polynomial ring over $k[x_1,...,x_(n-1)]$) is also countable. This finishes the induction.

    \ 

  2. #text(weight: "bold")[There are at most countable ideals for $k[x_1,...,x_n]$:]
  
    Based on Hilbert's Basis Theorem, since $k$ is a field (in particular a Noetherian Ring), $k[x_1,...,x_n]$ is a Noetherian Ring. Hence, all ideals of $k[x_1,...,x_n]$ are finitely generated. 

    Now, for each ideal $I$, fix a specific finite set of generators (say $I=(f_1,...,f_i)$), then let $S = {"all finite subset of "k[x_1,...,x_n]}$, there is a clear inclusion from $Sigma = {"ideals "I subset.eq k[x_1,...,x_n]}$ to $S$, by $I mapsto {f_1,...,f_i}$ (the fixed finite set of generators).

    Finally, because $k[x_1,...,x_n]$ is countable, let $(f_i)_(i=0)^infinity$ be an ordering of $k[x_1,...,x_n]$ using natural numbers. Then, for any finite subset $T subset k[x_1,...,x_n]$, it contains some largest index, say $i_T in NN$, in particular $T in cal(P)({f_0,...,f_(i_T)})$ (the power set of ${f_0,...,f_(i_T)}$). So as a set, one has $S subset.eq union.big_(i=0)^infinity cal(P)({f_0,...,f_i})$. Because the index is countable, and each $cal(P)({f_0,...,f_i})$ is finite, then the union $union.big_(i=0)^infinity cal(P)({f_0,...,f_i})$ is countable, which its subset $S$ is also countable.

    As a result, because the set of ideals $Sigma$ can be identified as a subset of $S$, $Sigma$ is also countable, showing $k[x_1,...,x_n]$ has countable ideals. In particular, $Spec(k[x_1,....,x_n])$ is also countable (since it collects all prime ideals of $k[x_1,...,x_n]$).

  \ 

  Finally, since each $Spec(k[x_1,...,x_n])$ is countable, because $cal(O)(U_j)$ is a quotient of $k[x_1,...,x_n]$ (for some positive integer $n$), then $Spec(cal(O)(U_j)) = U_j$ is also countable. Then, because $X = union.big_(j)U_j$, with the index being finite, $X$ itself must be countable as set, hence has at most countably many points. #place(right, $ballot$) 
]

#pagebreak()

= D//4
#problem[
  Let $X$ be a scheme which is covered by two affine open subschemes. Prove or disprove that $X$ is affine.

  \ 

  #line(length: 100%)

  \
][
  /*Counterexample: $CC PP^1$ can be covered by two affine spaces. Given $AA^1_CC = Spec(CC[x])$, the gluing map between two copies of $AA^1_CC\\{0}$ is $(x-z) mapsto (x-1/z)$ (corresponding to the gluing map $z mapsto 1/z$ when creating two projective spaces).

  \ 
  */
  Here, we'll prove that $X$ is not necessarily affine, by constructing a counterexample.

  \ 

  Consider the two schemes $Y=Z=AA^1_CC= Spec(CC[t])$, and consider $U= AA^1_CC\\{(t)}$ (where $(t)$ corresponds to the maximal ideal for origin $0 in CC$). Then, take the identity map $f=id_U:U arrow.tilde U$, the inclusion $iota_U:U arrow.hook Y=Z$, and consider $X = Y union.sq_f Z$ as the gluing of schemes:

  #set align(center)
  #diagram($
             U edge("hook->", script(iota_U)) edge("d","hook->", script(iota_U)) edge("dr", ->, script(theta)) & Y edge("d",->, script(iota_Y))\ 
             Z edge(->, script(iota_Z)) & X=Y union.sq_f Z
           $)
  #set align(left)

  (Note: $theta$ is the composition of the morphisms of schemes).

  Which, $X$ is clearly covered by $Y$ and $Z$ (or the image of them under the canonical inclusion maps), which both open subsets are affine. Yet, we'll prove that $X$ itself is not affine via contradiction:

  \ 
  
  Suppose the contrary that $X$ is an affine scheme. If consider the evaluation of the structure sheaves, one induce the following morphisms:

  #set align(center)
  #diagram($
             cal(O)(U) & cal(O)(Y) edge("l",->, script(iota_U^*)) \ 
             cal(O)(Z) edge("u",->, script(iota_U^*), #left) & cal(O)(X) edge("l",->, script(iota_Z^*), #left) edge("u",->, script(iota_Y^*))
           $)
  #set align(left)
  Where, $cal(O)(X)$ together with the rihg homomorphisms $iota_Y^*, iota_Z^*$ form a fibre product of the to ring homomorphisms $iota_U^*:cal(O)(Y)=cal(O)(Z)->cal(O)(U)$.

  \ 

  Notice that since $U = AA^1_CC\\{(t)}$, it denotes all the prime ideals in $CC[t]$, which is of the form $(t-a)$ for some $a != 0$. So, since if $a!=0$ then $t in.not (t-a)$ (because $a$ is not a solution of $t$, so $(t-a) divides.not t$), and $t$ is irreducible in $CC[t]$ (a PID), showing $(t)$ is the only prime (hence maximal) ideal containing $t$. This proves that $U = D(t)$, the open set consists of all prime ideals not containing $t in CC[t]$.

  As a result, $cal(O)(U) = cal(O)(D(t)) = CC[t]_t tilde.equiv (CC[t])[x]\/(x t-1)$; and, with $Y=Z=AA^1_CC$, $cal(O)(Y)=cal(O)(Z) = cal(O)(Spec(CC[t])) = CC[t]$. This shows that $iota_U^*:CC[t] -> CC[t]_t$ is given by composing the inclusion $CC[t] arrow.hook (CC[t])[x]$ and projection $(CC[t])[x]->> (CC[t])[x]\/(t x-1)$. 
  
  Here, we'll prove that the ring homomorphism $iota^*_U: CC[t]-> (CC[t])[x]\/(t x-1)$ is injective (for later purpose): If $f in CC[t] arrow.hook (CC[t])[x]$ has $f in (t x-1)$, notice that as a polynomial ring over $CC[t]$, one has $deg_x (f)=0$, if $f = g dot (t x-1)$ for some $g in (CC[t])[x]$, then $f=0$ (since if $f!=0$, then $0=deg_x (f)= deg_x (g dot (t x-1))>= deg_x (t x-1) = 1$, which is a contradiction). Therefore, for $f in CC[t] arrow.hook (CC[t])[x]$, one has $overline(f)=0 in (CC[t])[x]\/(t x-1)$ iff $f in (t x-1)$ iff $f=0$, showing the map $iota^*_U: CC[t]-> (CC[t])[x]\/(t x-1)$ is injective.

  \ 

  However, since $iota_U^*:cal(O)(Y)=cal(O)(Z)-> cal(O)(U)$ are just two identical maps (since they're induced by the same morphism of schemes), then their fibre product is in fact themselves together with identity, so $cal(O)(X) tilde.equiv cal(O)(Y)=cal(O)(Z) = CC[t]$, and $iota_Y^* = iota_Z^* = id_(CC[t])$.
  
  (Note: Take $cal(O)(X)=cal(O)(Y)=cal(O)(Z)=CC[t]$ and $iota_Y^*=iota_Z^* = id_(CC[t])$ definitely satisfies the fibre square, because the two maps taking fibre product are identical; Now, given any commutative ring $B$ together with ring homomorphisms $i_Y:B-> cal(O)(Y)$ and $i_Z:B->cal(O)(Z)$ such that $iota^*_U compose i_Y = iota^*_U compose i_Z$, i.e. $B$ with $i_Y,i_Z$ satisfies the fibre squares; then, because $iota_U^*$ is proven to be injective, then it enforces $i_Y=i_Z$ as set maps. So, $i_Y=i_Z:B->cal(O)(Y)=cal(O)(Z) = CC[t]$ is the unique map satisfying $id_(CC[t]) compose i_Y = i_Y$, and $id_(CC[t]) compose i_Z = i_Z$). 
  
  \ 

  Finally, since $X$ is assumed to be affine, and $cal(O)(X) = CC[t]$ based on the above observation, one has $X = Spec(CC[t]) = AA^1_CC$. Yet, notice that this creates a contradiction: 
  
  Recall that morphisms between affine schemes must be generated by unique ring homomorphism between their corresponding rings. Which, $iota_Y:Y -> X$ is induced by $iota^*_Y = id_(CC[t]):cal(O)(X)->cal(O)(Y)$ (or $iota_Y = (iota^*_Y)^*$); however, notice that taking the induced morphism of affine schemes of $id_(CC[t])$, we get $(id_(CC[t]))^*:Y->X$, which is precisely the identity on $X=Spec(cal(O)(X))=Y=Spec(cal(O)(Y))=Spec(CC[t])$, this contradicts the fact that $iota_Y: Y -> X$ is not surjective (since when taking the adjunction space, the ideal $z = (t) in Z$ is not part of $U = AA^1_CC\\{(t)}$, hence when taking $X = Y union.sq_f Z$, $z in.not im(iota_Y)$).

  \ 

  Since we reaches a contradiction, then our assumption is false, which $X$ cannot be affine. Therefore, it's a desired counterexample for this statement. #place(right, $ballot$)
]

#pagebreak()

= D//5
#problem[
  Let $A=RR[X_1,X_2,X_3]\/(X_2-X_1^2, X_3-X_1^3)$ and $X=Spec(A)$. Let $f(X_1,X_2,X_3) = a_1X_1+a_2X_2+a_3X_3+a_4$, where $a_i in RR$ and $Y=Spec(RR[X_1,X_2,X_3]\/(f))$. Is the set $X sect Y$ finite? If yes, what is a finite upper bound on its cardinality? Explain your answer with complete argument.

  \ 

  #line(length: 100%)

  \
][
  /*It's equivalent to say that the set $(t,t^2,t^3) subset.eq RR^3$ has only finite intersection with a plane. Which is always true, since the plane $a_1x^1+a_2x_2+a_3x_3+a_4=0$ plugging in the set has $a_1t+a_2t^2+a_3t^3+a_4 = 0$, which is a degree 3 $RR$-polynomial, so the bound of the intersection must be $3$. (Here it's a bit more complicated, because $RR$ is not algebraically closed...)

  \ 

  Some tools: For an integral domain $B$ that's a finitely-generate $k$-algebra ($k$ a field, not necessarily algebraically close), then the Krull dimension of $B$ equals the transcedental degree of $F(B)$, its fraction field as a $k$-algebra over $k$.

  \ 

  Step 1: Argue that the first ring has krull dimension $1$, the second ring has krull dimension 2 (by proving they're isomorphic to $RR[t]$ and $RR[s,u]$). In other words, the first prime ideal has height 2, the second has height 1.

  Step 2: Argue they're not including each other. So, if a prime ideal contains both (i.e. in $X sect Y$ when viewed them as subspaces in $Spec(RR[x_1,x_2,x_3])$), it must properly contain the two. With the second one already at height $2$, this proper containment makes the larger prime ideal height $3$ (matching the krull dimension of $RR[x_1,x_2,x_3]$), hence it's maximal.

  Step 3: Construct a quotient and show that the quotient is isomorphic to either $RR$ or $CC$ (i.e. it always embedds into $CC$) by some fixed evaluation. Then, argue that this evaluation must have $x_2-x_1^2$, $x_3-x_1^3$,and $a_1 x_1+a_2x_2+a_3x_3+a_4$ all being $0$ (by fixing $x_1$). Then, show there's only $3$ such possibility.

  \ 

  #line(length: 100%)

  \ 
  */
  We'll prove that $X sect Y$ is not necessarily finite, by showing it's infinite for $f=0$. 
  //(For safety, we'll also prove that $f!=0$ implies $X sect Y$ is finite, and has a bound on its cardinality being $3$).

  \ 
  
  Here we denote $I = (X_2-X_1^2, X_3-X_1^3)$, and utilized the fact that $X = Spec(RR[X_1,X_2,X_3]\/I) tilde.equiv V(I)$, and $Y=Spec(RR[X_1,X_2,X_3]\/(f)) tilde.equiv V((f))$ in $Spec(RR[X_1,X_2,X_3])$. Which, the intersection $X sect Y$ is precisely all the prime ideals $P subset RR[X_1,X_2,X_3]$ that contains both $I$ and $(f)$.

  Here's an order of the proof: 
  1. Show that $RR[X_1,X_2,X_3]\/I tilde.equiv RR[t]$. //which is a PID (where all prime ideals are maximal)
  2. Show that $X sect Y$ has a one-to-one correspondance to a specific subset of $Spec(RR[t])$.
  3. Deduce $X sect Y$ is infinite for the case $f=0$.
  //4. (Extra:) Show that for $f!=0$, $X sect Y$ is finite, and has 3 as upper bound of its cardinality.

  \ 

  #text(weight: "bold")[Proof of (1):]

  Consider the evaluation map $phi:RR[X_1,X_2,X_3]->> RR[t]$ by $phi(f(X_1,X_2,X_3)) = f(t, t^2, t^3)$. If consider $X_2-X_1^2, X_3-X_1^3$ (the generators of $I$), one has the following:
    $ phi(X_2-X_1^2) = t^2-(t)^2 = 0, quad phi(X_3-X_1^3)= t^3-(t)^3 = 0 $
    This shows that $X_2-X_1^2, X_3-X_1^3 in ker(phi)$, so $I subset.eq ker(phi)$. 

    Now, we argue that $I = ker(phi)$: Given any monomial $X_1^(n_1)X_2^(n_2)X_3^(n_3)$, then one has the following equality:
    $ X_1^(n_1)X_2^(n_2)X_3^(n_3) &= (X_1^(n_1)X_2^(n_2)X_3^(n_3) - X_1^(n_1+2 n_2)X_3^(n_3))+X_1^(n_1+2 n_2)X_3^(n_3)\ 
    &= X_1^(n_1)X_3^(n_3)(X_2^(n_2)-X_1^(2 n_2))+(X_1^(n_1+2n_2)X_3^(n_3) - X_1^(n_1+2n_2+3n_3))+X_1^(n_1+2n_2+3n_3)\ 
    &= X_1^(n_1)X_3^(n_3)(sum_(i=0)^(n_2-1)X_2^i (X_1^2)^(n_2-i-1))(X_2-X_1^2) + X_1^(n_1+2n_2)(X_3^(n_3)-X_1^(3n_3))+X_1^(n_1+2n_2+3n_3)\ 
    &= X_1^(n_1)X_3^(n_3)(sum_(i=0)^(n_2-1)X_2^i (X_1^2)^(n_2-i-1))(X_2-X_1^2) + X_1^(n_1+2n_2)(sum_(j=0)^(n_3-1)X_3^j(X_1^3)^(n_3-j-1))(X_3-X_1^3)+X_1^(n_1+2n_2+3n_3)  $
    Hence, all monomials can be written as $X_1^(n_1)X_2^(n_2)X_3^(n_3) = f dot (X_2-X_1^2)+g dot (X_3-X_1^3) + X_1^k$ for some $f,g in RR[X_1,X_2,X_3]$, and $k in NN$. As a result, all polynomials $h(X_1,X_2,X_3) = f dot (X_2-X_1^2)+g dot (X_3-X_1^3) + h_1(X_1)$ for some $f,g in RR[X_1,X_2,X_3]$, and $h_1(t) in RR[t]$.

    So, one has $h in ker(phi)$ iff $phi(h) = h_1(t)=0$ (since $X_2-X_1^2, X_3-X_1^3$ are evaluated to $0$), which happens iff $h(X_1,X_2,X_3) = f dot (X_2-X_1^2)+g dot (X_3-X_1^3) in I$. This concludes that $I = ker(phi)$. As a result, $RR[X_1,X_2,X_3]\/I tilde.equiv RR[t]$.

    \ 

    #text(weight: "bold")[Proof of (2):]

    Since $(X sect Y) subset X = Spec(RR[X_1,X_2,X_3]\/I) tilde.equiv Spec(RR[t])$, it's naturally identified as a subset of prime ideals of $RR[t]$ (the identification $(X sect Y)-> Spec(RR[t])$ is by $P mapsto phi(P)$, where $P$ is the evaluation map defined in (1)). 

    Notice that all prime ideals $P in (X sect Y)$ also contains $f=a_1X_1+a-2X_2+a_3X_3+a_4$, hence it satisfies $phi(f) = a_1t+a_2t^2+a_3t^3+a_4 in phi(P)$, so $X sec subset.eq V((a_1t+a_2t^2+a_3t^3+a_4)) subset Spec(RR[t])$.
    
    Conversly, given prime ideal $overline(P) in V((a_1t+a_2t^2+a_3t^3+a_4))$, then under the preimage of ealuation map, one has $f=a_1X_1+a_2X_2+a_3X_3+a_4 in phi^(-1)(a_1t+a_2t^2+a_3t^3+a_4) subset phi^(-1)(overline(P))$, showing that $phi^(-1)(overline(P))$ is a prime ideal containing both $I$ and $(f)$, which is in $X sect Y$. Therefore, set wise one can conclude that $X sect Y = V((a_1t+a_2t^2+a_3t^3+a_4))$.

  \ 

  #text(weight: "bold")[Proof of (3):]

  Part (2) provides that $X sect Y = V((a_1t+a_2t^2+a_3t^3+a_4))$ as set bijection. However, if take $f=a_1X_1+a_2X_2+a_3X_3+a_4=0$, this ideal becomes $(0)$, hence $X sect Y = V((0))$, which is exactly $Spec(RR[t])$. However, $Spec(RR[t])$ is infinite (since $t-a in RR[t]$ is irreducible for all $a in RR$, so $(t-a)$ is a distinct prime ideal in $Spec(RR[t])$). Hence, $f=0$ is a case where $X sect Y$ is infinite, showing $X sect Y$ is not necessarily finite. This completes the proof. #place(right, $ballot$)

  \ 

  //#text(weight: "bold")[(Extra) Proof of (4):]

  
]