#import "../../macros.typ": *

//setup basics
#import "@preview/rubber-article:0.4.1": *
#import "@preview/ergo:0.2.0": *
#import "@preview/fletcher:0.5.5" as fletcher: *

//basic template setup
#show: article.with(
  header-display: true,
  eq-numbering: "(1.1)",
  eq-chapterwise: true,
  margins: 1.0in,
)
#show: ergo-init.with(
    colors: ergo-colors.bw,  
    styles: ergo-styles.sidebar2, 
    breakable: true,
    inline-qed: true
)

//start document
#maketitle(
  title: "Math 220B Midterm",
  authors: ("Zih-Yu Hsieh",),
  date: datetime.today().display("[month repr:long] [day], [year]"),
)

= ND//1
#problem[
  Let $A$ be a commutative ring. Prove or disprove that $A$ is a local ring if and only if $A[[x]]$ is a local ring.
][
  
]

\ 

= ND//2
#problem[
  Let $A$ be a commutative ring and $a!=0$ be an element of $A$. Prove or disprove that we can find a multiplicatively closed subset $S subset A$ such that the image of $a$ under the localization $A -> S^(-1)A$ lies in every maximal ideal of $S^(-1)A$.
][]

\ 

= ND//3
#problem[
  Let $A$ be a finite integral domain. Prove or disprove that $A$ is a quotient of $ZZ$.
][]

\ 

= ND//4
#problem[
  Let $A$ be a commutative ring. Prove or disprove that the canonical map $(A[X,Y])/((X Y))-> A[X] times A[Y]$, given by $f(X,Y) mapsto (f(X,0), f(0,Y))$, is an isomorphism of rings.
][]

\ 

= ND//5
#problem[
  Let $A$ be a commutative ring and $B=A[X_1,...,X_n]\/I$ for some maximal ideal $I subset A[X_1,...,X_n]$. Prove or disprove that under the canonical composite ring homomorphism $A -> A[X_1,...,X_n]->> B$, $B$ is a finitely generated $A$-module (i.e., generated by finitely many elements as an $A$-module).
][]