#import "../../macros.typ": *

//setup basics
#import "@preview/rubber-article:0.4.1": *
#import "@preview/ergo:0.2.0": *
#import "@preview/fletcher:0.5.5" as fletcher: *

//basic template setup
#show: article.with(
  header-display: true,
  eq-numbering: "(1.1)",
  eq-chapterwise: true,
  margins: 1.0in,
)
#show: ergo-init.with(
    colors: ergo-colors.bw,  
    styles: ergo-styles.basic, 
    breakable: true,
    inline-qed: true
)

//start document
#maketitle(
  title: "Math 220B Final",
  authors: ("Zih-Yu Hsieh",),
  date: datetime.today().display("[month repr:long] [day], [year]"),
)

#set enum(numbering: "(1)")

= ND (Type up the idea)//1
#problem[
  Let $R$ be a commutative ring such that $R_frak(m)$ is a Noetherian ring for every maximal ideal $frak(m)$. Prove or disprove that $R$ is Noetherian.

  \ 

  #line(length: 100%)

  \ 
][
  Test: Consider the direct product ring $R=product_(n=0)^infinity ZZ\/2ZZ$. Then, its maximal ideal must necessarily be of the form $m_i = product_(n!=i)ZZ\/2ZZ$ (the only maximal ideal times other whole copies of ring). Then, anything not in this maximal ideal $m_i$ is of the form  $(a_0,...,a_i=1,...)$.

  Now, if the following holds in localization:
  $ ((a_0,a_1,...,a_i,...))/((s_0,s_1,...,1,...))=((b_0,b_1,...,b_i,...))/((t_0,t_1,...,1,...)) $
  Then, there must exists $(u_0,u_1,...,1,...) in R\\m_i$, such that the following holds:
  $ &((a_0,a_1,...,a_i,...)(t_0,t_1,...,1,...)-(b_0,b_1,...,b_i,...)(s_0,s_1,...,1,...))(u_0,u_1,...,1,...)= 0\
  \
  & (a_0 t_0-b_0 s_0,a_1 t_1-b_1 s_1,...,a_i-b_i,...)(u_0,u_1,...,1,...)=0\ 
  \
  & (u_0(a_0 t_0-b_0 s_0),u_1(a_1 t_1-b_1 s_1),...,a_i-b_i,...)=0 $
  Which, the equality implies $a_i-b_i=0$, or $a_i-b_i$; conversely, if $a_i=b_i$, then take $(u_0,u_1,...,1,...) in R\\m_i$ such that any $j!=i$ satisfies $u_j=0$, the above equality then shows the two fractions are equal (since the other coordinates are $0$ by multiplying $u_j$).

  As a result, one has $R_(m_i) tilde.equiv ZZ\/2ZZ$ a field, hence Noetherian. But, $R$ itself is clearly not Noetherian (by increasing the ideals)
]

#pagebreak()

= ND (Type up the idea)//2
#problem[
  Let $A$ and $B$ be Noetherian rings together with surjective ring homomorphisms $f:A->C$ and $g:B->C$. Let $D=A times_C B = {(a,b) in A times B | f(a)=g(b)}$ be the subring of the direct product ring $A times B$. Prove or disprove that $D$ is a Noetherian ring.

  \ 

  #line(length: 100%)

  \ 
][
  Idea: It must be Noetherian.

  Try to prove the map $A times_C B ->> A->> C$ has kernel being exactly $ker(f) times ker(g)$, which it forms the following exact sequence as $A times_C B$-module:
  $ 0-> ker(f) times ker(g) -> A times_C B ->> C -> 0 $
  Notice that since $ker(f) subset.eq A$ and $ker(g) subset.eq B$ are finitely generated by Noetherian Property (say $ker(f)=(a_1,...,a_n), ker(g)=(b_1,...,b_m)$), then, $(a_1,0),...,(a_n,0), (0,b_1),...,(0,b_m)$ generates $ker(f) times ker(g)$: Here, it uses the fact that any $a in A$ has some $b in B$, such that $(a,b) in A times_C B$ (by surjectivity of $f,g$). As a result, any $k in ker(f), l in ker(g)$, there exists $r_1,...,r_n in A, s_1,...,s_m in B$, such that $k=r_1 a_1+...+r_n a_n$ and $l = s_1 b_1+...+s_m b_m$.  Suppose $(r_1,p_1),...,(r_n,p_n),(q_1,s_1),...,(q_m,s_m) in A times_C B$, then we have the following:
  $ &(r_1,p_1)(a_1,0)+...+(r_n,p_n)(a_n,0)+(q_1,s_1)(0,b_1)+...+(q_m,s_m)(0,b_m)\ 
  &= (r_1 a_1,0)+...+(r_n a_n,0)+(0,s_1 b_1)+...+(0, s_m b_m)\ 
  &= (r_1 a_1+...+r_n a_n, s_1 b_1+...+s_m b_m)\ 
  &= (k,l) $
  Hence, $ker(f) times ker(g)$ is a fin. gen. $A times_C B$-module. 

  \

  This ideal is Noetherian $A times_C B$-module, simply because as $A times_C B$-module, it's isomorphic to $ker(f) plus.circle ker(g)$, which each are Noetherian $A times_C B$-module.

  So, the exact sequence forces $A times_C B$ to be Noetherian over itself, and hence a Noetherian ring.
]

#pagebreak()

= ND (Type the idea up)//3
#problem[
  Let $R$ be a commutative local ring with maximal ideal $frak(m)$. Assume that $frak(m)$ is principal and $sect.big_(n>=1)frak(m)^n=(0)$. Prove or disprove that $R$ is Noetherian.

  \ 

  #line(length: 100%)

  \ 
][
  Idea: $R$ is not necessarily Noetherian. Consider $R=k[x_1,...]\/(x_1^2,...)$ (which has infinite indeterminates), which $R$ is clearly not Noetherian (by choosing $(overline(x_1)) subset (overline(x_1),overline(x_2)) subset ...$ as the ascending chain). 
  
  Then, we claim that $frak(m)=(overline(x_1),...) subset.eq R$ is maximal.

  On the other hand, each $frak(m)^n$ must be generated by $overline(x_(i_1))...overline(x_(i_m))$, where each $i_j$ are distinct, and $m>=n$ (since all the powers $>=2$ for the same indeterminate gets killed by the quotient). So, the intersection $sect.big_(n>=1)frak(m)^n=(0)$.
]

#pagebreak()

= ND//4
#problem[
  Is there an integral domain $R$ whose all maximal ideals are principal but $R$ is not a PID? Justify your answer.

  \ 

  #line(length: 100%)

  \ 
][
  Test: Take all analytic function that's $[0,1]->RR$ (which is an integral domain, since any analytic function with dense $0$ must be identically $0$).

  Note: the ideal $(x-a)$ generated by $x-a$ for all $a in RR$ is maximal (by suitable power series expansion, and factoring $x-a$ out).

  On the other hand, any other ideal not this form (while "claimed" to be maximal) is the unit ideal (by compactness, and the fact that we can square functions over this ring, cf. Aluffi for proof).

  So, all maximal ideals are principal (wait but then the ideals may be principal sill...fuck)

  \ 

  This is a PID, fuck (since every function are only allowed to have finitely many zeros on $[0,1]$, so it can only be factored finitely many times; also, every irreducible elements must be of the form $(x-a)h(a)$ where $h(a)!=0$ at all $a in [0,1]$, so all irreducibles are prime, and they generates maximal ideal).

  \ 

  Maybe this is false. What if we look at the set of non-principal ideals? $Sigma$ denotes such set, it definitely has an upper bound for each chain, hence has a maximal element $J$. Q: Is $J$ maximal? $J$ is prime this is known. 
]

#pagebreak()

= ND (Type the ideal up)//5
#problem[
  Let $R$ be an integral domain in which the set of principal ideals satisfies the ascending chain condition. Prove or disprove that $R$ is Noetherian.

  \ 

  #line(length: 100%)

  \ 
][
  Idea: In a UFD, its principal ideals satisfies the ascending chain condition (because of unique factorization, and each strict inclusion of principal ideals must decrease in the number of irreducible factors). So, to provide a counterexample, it suffices to provide a UFD that's not Noetherian.

  EX: $k[x_1,...]$, since every polynomial can be included into a polynomial ring with finite indeterminate, then it necessarily has a factorization (and it is unique, simply because any two factorizations can be included into the same finite indeterminate polynomial rings, by choosing enough polynomials). So, it's a UFD, but on the other hand it's not Noetherian (consider $(x_1) subset (x_1,x_2) subset ...$ a strict inclusion of ideal, or copy the proof that the ideal $(x_1,...)$ is not finitely generated).
]