#import "../../macros.typ": *

//setup basics
#import "@preview/rubber-article:0.4.1": *
#import "@preview/ergo:0.2.0": *
#import "@preview/fletcher:0.5.5" as fletcher: *

//basic template setup
#show: article.with(
  header-display: true,
  eq-numbering: "(1.1)",
  eq-chapterwise: true,
  margins: 1.0in,
)
#show: ergo-init.with(
    colors: ergo-colors.bw,  
    styles: ergo-styles.basic, 
    breakable: true,
    inline-qed: true
)

//start document
#maketitle(
  title: "Math 220B Final",
  authors: ("Zih-Yu Hsieh",),
  date: datetime.today().display("[month repr:long] [day], [year]"),
)

#set enum(numbering: "(1)")

= ND//1
#problem[
  Let $R$ be a commutative ring such that $R_frak(m)$ is a Noetherian ring for every maximal ideal $frak(m)$. Prove or disprove that $R$ is Noetherian.

  \ 

  #line(length: 100%)

  \ 
][]

#pagebreak()

= ND//2
#problem[
  Let $A$ and $B$ be Noetherian rings together with surjective ring homomorphisms $f:A->C$ and $g:B->C$. Let $D=A times_C B = {(a,b) in A times B | f(a)=g(b)}$ be the subring of the direct product ring $A times B$. Prove or disprove that $D$ is a Noetherian ring.

  \ 

  #line(length: 100%)

  \ 
][
  Idea: It must be Noetherian.

  Try to prove the map $A times_C B ->> A->> C$ has kernel being exactly $ker(f) times ker(g)$, which it forms the following exact sequence as $A times_C B$-module:
  $ 0-> ker(f) times ker(g) -> A times_C B ->> C -> 0 $
  Notice that since $ker(f) subset.eq A$ and $ker(g) subset.eq B$ are finitely generated by Noetherian Property (say $ker(f)=(a_1,...,a_n), ker(g)=(b_1,...,b_m)$), then, $(a_1,0),...,(a_n,0), (0,b_1),...,(0,b_m)$ generates $ker(f) times ker(g)$: Here, it uses the fact that any $a in A$ has some $b in B$, such that $(a,b) in A times_C B$ (by surjectivity of $f,g$). As a result, any $k in ker(f), l in ker(g)$, there exists $r_1,...,r_n in A, s_1,...,s_m in B$, such that $k=r_1 a_1+...+r_n a_n$ and $l = s_1 b_1+...+s_m b_m$.  Suppose $(r_1,p_1),...,(r_n,p_n),(q_1,s_1),...,(q_m,s_m) in A times_C B$, then we have the following:
  $ &(r_1,p_1)(a_1,0)+...+(r_n,p_n)(a_n,0)+(q_1,s_1)(0,b_1)+...+(q_m,s_m)(0,b_m)\ 
  &= (r_1 a_1,0)+...+(r_n a_n,0)+(0,s_1 b_1)+...+(0, s_m b_m)\ 
  &= (r_1 a_1+...+r_n a_n, s_1 b_1+...+s_m b_m)\ 
  &= (k,l) $
  Hence, $ker(f) times ker(g)$ is a fin. gen. $A times_C B$-module. In particular, this proof is doable for any submodule $I times J subset.eq ker(f) times ker(g)$


  \ 

  #text(weight: "bold")[Problem: ]the kernel is finitely generated doesn't imply every of its submodule is finitely generated (Here $C$ has no problem, as it's already a Noetherian $A$-mod / $B$-mod, so it's naturally a Noetherian $A times_C B$-Mod)
]

#pagebreak()

= ND (Type the idea up)//3
#problem[
  Let $R$ be a commutative local ring with maximal ideal $frak(m)$. Assume that $frak(m)$ is principal and $sect.big_(n>=1)frak(m)^n=(0)$. Prove or disprove that $R$ is Noetherian.

  \ 

  #line(length: 100%)

  \ 
][
  Idea: $R$ is not necessarily Noetherian. Consider $R=k[x_1,...]\/(x_1^2,...)$ (which has infinite indeterminates), which $R$ is clearly not Noetherian (by choosing $(overline(x_1)) subset (overline(x_1),overline(x_2)) subset ...$ as the ascending chain). 
  
  Then, we claim that $frak(m)=(overline(x_1),...) subset.eq R$ is maximal.

  On the other hand, each $frak(m)^n$ must be generated by $overline(x_(i_1))...overline(x_(i_m))$, where each $i_j$ are distinct, and $m>=n$ (since all the powers $>=2$ for the same indeterminate gets killed by the quotient). So, the intersection $sect.big_(n>=1)frak(m)^n=(0)$.
]

#pagebreak()

= ND//4
#problem[
  Is there an integral domain $R$ whose all maximal ideals are principal but $R$ is not a PID? Justify your answer.

  \ 

  #line(length: 100%)

  \ 
][]

#pagebreak()

= ND (Type the ideal up)//5
#problem[
  Let $R$ be an integral domain in which the set of principal ideals satisfies the ascending chain condition. Prove or disprove that $R$ is Noetherian.

  \ 

  #line(length: 100%)

  \ 
][
  Idea: In a UFD, its principal ideals satisfies the ascending chain condition (because of unique factorization, and each strict inclusion of principal ideals must decrease in the number of irreducible factors). So, to provide a counterexample, it suffices to provide a UFD that's not Noetherian.

  EX: $k[x_1,...]$, since every polynomial can be included into a polynomial ring with finite indeterminate, then it necessarily has a factorization (and it is unique, simply because any two factorizations can be included into the same finite indeterminate polynomial rings, by choosing enough polynomials). So, it's a UFD, but on the other hand it's not Noetherian (consider $(x_1) subset (x_1,x_2) subset ...$ a strict inclusion of ideal, or copy the proof that the ideal $(x_1,...)$ is not finitely generated).
]